site_name: Estadia Já
theme:
  name: material

nav:
  - 'Início': 'index.md'
  - 'Modelagem': 'diagramas/index.md'
  - 'Arquitetura': 'arquitetura/index.md'
  - 'Banco de Dados': 'banco-de-dados/index.md'
  - 'Desenvolvimento':
    - 'Visão Geral': 'desenvolvimento/index.md'
    - 'Backend': 'desenvolvimento/backend/index.md'
    - 'Frontend': 'desenvolvimento/frontend/index.md'
    - 'Docker': 'desenvolvimento/docker/index.md'
